### PR TITLE
Implement HD item shop pools

### PR DESCRIPTION
**Pull request by estebanfer**
- [x] Replace shop items using HD item pools
- [x] Change pet shop to only have one pet
- [x] Change hired hand shop to only have hired hands
- [x] Add bomb and tutorial shops (tutorial shop type, not implemented in tutorial)
- [x] Make black market character unlock to work
- [x] Add present item chance

Part of #148

### CODE REVIEW

**Comment by SuperNinjaFat** [comment]
I can try making the black market character work tomorrow
Was there anything in your HD findings that made the tutorial shop different from regular shops?

**Comment by estebanfer** [comment]
> Was there anything in your HD findings that made the tutorial shop different from regular shops?
They only have bomb bags and ropes

**Comment by SuperNinjaFat** [comment]
> > Was there anything in your HD findings that made the tutorial shop different from regular shops?
> 
> It only has bomb bags and ropes

Ah ok

**Comment by SuperNinjaFat** [comment]
The ankh isn't at $50,000. That's weird
image

**Comment by estebanfer** [comment]
> I don't know if this is a bug specific to these changes, but the ankh isn't at $50,000. Apart from that, so far everything seems good!

Uh I just tried and I see it at $50,000

**Comment by SuperNinjaFat** [comment]
> > I don't know if this is a bug specific to these changes, but the ankh isn't at $50,000. Apart from that, so far everything seems good!
> 
> Uh I just tried and I see it at $50,000

Weird! We'll just have to keep an eye out for it. If it shows up again, I guess we can try setting it in a timeout.

**Comment by estebanfer** [comment]
There was already code to spawn the BM character right? Where was it?

**Comment by SuperNinjaFat** [comment]
> There was already code to spawn the BM character right? Where was it?

https://github.com/SuperNinjaFat/HDmod/blob/1c84a76de380ad4b26537ea7f01eed1b3bec011f/lib/unlocks.lua#L233

**Comment by estebanfer** [comment]
Oh also, I forgot about the option to enable S2 shops, should an issue be made about that?

**Comment by SuperNinjaFat** [comment]
> Oh also, I forgot about the option to enable S2 shops, should an issue be made about that?

Sure, and it doesn't need a milestone set since I think it's not a high priority

**Pull request merged**
