### PR TITLE
fix anubis spawn validation, spawn only on path

### LINKED ISSUE #410: Improve Anubis spawn validation method
Anubis can spawn directly inside pushblocks and other things that frag him instantly. This happens too often to ignore! Improve his spawn validation code to avoid those kinds of entities.

### PR DESCRIPTION
**Pull request by estebanfer**
Closes #410

### CODE REVIEW

**Comment by SuperNinjaFat** [comment]
Looks good!

**Comment by estebanfer** [comment]
I think there's a problem, seems that procedural spawns are after extra spawns, and tikitraps are procedural, so they probably could spawn on anubis (after he spawned) and still kill him

**Comment by estebanfer** [comment]
solving #429 may fix that issue

**Comment by estebanfer** [comment]
actually maybe I'm wrong, the tikitraps don't seem to be able to spawn where anubis did, but idk how they detect him and don't spawn there

**Comment by SuperNinjaFat** [comment]
ah ok

**Pull request merged**
